DIRS={Actor,Audio,Engine,GameSaveSerializer,Player,Video}
INC=-Isrc/ -Isrc/**/ -I/usr/local/include/

CC=g++-5
CXXFLAGS=-D=DEBUG -D=_DEBUG -D=DEBUG_TOOLS -pedantic -Wall -std=c++11 $(INC)
LDFLAGS=-L/usr/local/lib -lSDL2 -lSDL2_image -lSDL2_ttf -lSDL2_mixer -pthread -lc++

SOURCES=$(wildcard src/**/*.cpp) $(wildcard src/*.cpp)
OBJECTS=$(patsubst src/%.cpp, build/%.o, $(SOURCES))
EXECUTABLE=convenienced

all: $(EXECUTABLE)
	@echo "Created: $(EXECUTABLE)"
$(EXECUTABLE): $(OBJECTS)
	@echo "Linking objects..."
	@$(CC) $^ $(LDFLAGS) -o $@
build/%.o: src/%.cpp
	@echo "Building: $^..."
	@mkdir -p build/$(DIRS)
	@$(CC) $(CXXFLAGS) -c $^ -o $@
clean:
	@rm -f $(EXECUTABLE) $(OBJECTS)
