// ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: //
// Team USA - Software Engineering Project (Fall 2015).
// Legend of the Great Unwashed (Working Title).
// ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: //
/// \file ActorEvent.h
/// \brief Declares ActorEvent struct.
// ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: //

#pragma once

// ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: //

#include "Headers.h"

// ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: //

namespace USA {

    enum ActorEventType {
        Nil = -1,
        ChangeScene,
        LoadLevel,
        PlayAudio,
        NewGame,
        LoadGame,
        DisplayText,
        ExitGame,
        StreamAudio
    };

    ///
    /// \class ActorEvent
    /// \brief Event data generated by Actors, handled by Engine.
    struct ActorEvent {
        int32_t value;
        ActorEventType type;

        ActorEvent( void ) : value( -1 ), type( ActorEventType::Nil ) { }
    };

}

// ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: //
